baseURL: https://github.com/Nico-Casarin/ncasa-site/tree/master/public
languageCode: en-us
title: Nicola's site
copyright: Â© 2023 Nicola Casarin
# googleAnalytics:
# paginate specifies the maximum number of posts displayed on the home page.
paginate: 12
# theme specifies the name of the theme to be used.
theme: minima
# defaultContentLanguage specifies the default language to use.
defaultContentLanguage: en
# language.x setup
languages:
  en:
    languageName: EN # will be displayed in the navbar.
    weight: 1
    author:
      status: Work in progress ğŸš§

# author specifies your name, a slogon and your brief self-introduction.
author:
  name: Nicola Casarin
  status: Currently living in Europe ğŸŒ
  description: |
    This is my site :)

params:
  # greet specifies greeting words.
  greet: Hello there
  # subtitle speficies a subtitle displayed right after the site title.
  subtitle:
  # switch specifies two emojis used as the button toggling color themes.
  switch: ["ğŸŒš", "ğŸŒ"]
  # minima has one dark theme and multiple light themes. defaultTheme specifies
  # a default light theme to use. currently available options: light, sand, rock, system.
  defaultTheme: sand
  # displayDate speficies whether or not to display post date on the home page.
  displayDate: true
  # displayDescription specifies whether or not to display post description on
  # the hoem page.
  displayDescription: true
  # selectable specifies if or not your post content can be selected.
  selectable: true
  # social is an array containing as many as social accounts to be displayed
  # in the buttom of every page.
  social:
    # - name: "twitter"
    #   url: ""
    # - name: "email"
    #   url: ""
    - name: "github"
      url: "https://github.com/nico-casarin"
    # - name: "rss"
    #   url: "/index.xml"

  # math plugin
  math:
    enable: false
    provider: katex

  # diagram plugin
  diagram:
    enable: false
    provider: mermaid


# menu.main is an array containing what is used as the navigator.
# menu:
#   main:
#     - identifier: tags
#       name: "Tags"
#       weight: 2
#     - identifier: series
#       name: "Series"
#       weight: 3

# taxonomies defines ways to classify yout posts. Below are some presets that
# most bloggers use, so you can replace them with whatever you like.
taxonomies:
  category: categories
  tag: tags
  series: series

# markup.highlight has two keys set to make sure that the syntax highlighting
# in your posts are rendered correctly, so DO NOT edit them.
markup:
  highlight:
    lineNos: true
    noClasses: false